# Generated by Django 4.0.4 on 2022-05-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
